-- PostgreSQL schema for Supabase
-- Keep original MySQL schema in DoAnDaNganhDBSchema.sql unchanged.

begin;

create table if not exists public.users (
    "User_Id" bigint generated by default as identity primary key,
    username text not null unique,
    pass text not null,
    email text,
    "Name" text,
    date_of_birth date,
    social_security_number text,
    face_vector jsonb
);

alter table if exists public.users
    add column if not exists face_vector jsonb;

create table if not exists public.devicesensortype (
    serial_number text primary key,
    name text,
    model_number text,
    description text
);

create table if not exists public.devicesensor (
    device_id bigint generated by default as identity primary key,
    name text,
    properties jsonb,
    user_id bigint,
    serial_number text,
    constraint fk_devicesensor_user
        foreign key (user_id) references public.users("User_Id") on delete set null,
    constraint fk_devicesensor_type
        foreign key (serial_number) references public.devicesensortype(serial_number) on delete set null
);

create table if not exists public.automationrule (
    rule_id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    rule_description jsonb,
    device_id bigint,
    constraint fk_automationrule_device
        foreign key (device_id) references public.devicesensor(device_id) on delete cascade
);

create table if not exists public.usermodifyrule (
    modification_id bigint generated by default as identity primary key,
    user_id bigint,
    rule_id bigint,
    constraint fk_usermodifyrule_user
        foreign key (user_id) references public.users("User_Id") on delete cascade,
    constraint fk_usermodifyrule_rule
        foreign key (rule_id) references public.automationrule(rule_id) on delete cascade
);

create table if not exists public.devicestatelog (
    log_id bigint generated by default as identity primary key,
    activities text,
    device_id bigint,
    user_id bigint,
    rule_id bigint,
    created_at timestamptz not null default now(),
    constraint fk_devicestatelog_user
        foreign key (user_id) references public.users("User_Id") on delete set null,
    constraint fk_devicestatelog_device
        foreign key (device_id) references public.devicesensor(device_id) on delete cascade,
    constraint fk_devicestatelog_rule
        foreign key (rule_id) references public.automationrule(rule_id) on delete set null,
    constraint chk_devicestatelog_actor
        check (
            (user_id is not null and rule_id is null)
            or
            (user_id is null and rule_id is not null)
        )
);

commit;

-- Optional seed data
insert into public.users ("Name", username, pass, date_of_birth, social_security_number)
values
('Alice Smith', 'alice', '1234', date '1985-04-12', '123-45-6789'),
('Bob Johnson', 'john', '4321', date '1990-07-23', '987-65-4321')
on conflict (username) do nothing;

insert into public.devicesensortype (serial_number, name, model_number, description)
values
('SN001', 'Smart Thermostat', 'T1000', 'Regulates temperature'),
('SN002', 'Light Sensor', 'M2000', 'Detects movement')
on conflict (serial_number) do nothing;
