CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 60
STREAM_FPS = 30
STREAM_JPEG_QUALITY = 90
DETECTION_FPS = 15
STREAM_ANNOTATED = True
DETECTION_IMAGE_SIZE = 416

MODEL_PATH = "services/fall_detection/yolov8n-pose.pt"
PERSON_CLASS_ID = 0
DETECTION_CONFIDENCE = 0.55
YOLO_MAX_DETECTIONS = 4
SMOOTHING_ALPHA = 0.35
TARGET_LOST_SECONDS = 1.0

PID_X = {
    "kp": 0.05,
    "ki": 0.001,
    "kd": 0.01,
}

PID_Y = {
    "kp": 0.05,
    "ki": 0.001,
    "kd": 0.01,
}

FALL_ALERT_COOLDOWN_SECONDS = 10.0

# Fall-detection thresholds. These are intentionally conservative defaults;
# tune them with real camera clips from your deployment space.
MIN_KEYPOINT_CONFIDENCE = 0.35
FALL_HISTORY_SECONDS = 1.2
FALL_CONFIRM_SECONDS = 0.45
FALL_RECOVERY_SECONDS = 1.0
STATIC_LYING_SECONDS = 0.8
FALL_STILLNESS_SECONDS = 1.2
FALL_STILLNESS_CENTER_RATIO = 0.045
FALL_EDGE_MARGIN_RATIO = 0.08
FALL_OUT_OF_FRAME_SECONDS = 1.5

FALL_TORSO_ANGLE_DEGREES = 60.0
FALL_ASPECT_RATIO = 1.25
FALL_BOX_ONLY_ASPECT_RATIO = 2.0
FALL_ANGLE_SPEED_DEG_PER_SEC = 100.0
FALL_HEIGHT_DROP_RATIO = 0.22
FALL_CENTER_DROP_RATIO = 0.18
